-- MySQL Script generated by MySQL Workbench
-- Παρ 26 Ιουν 2020 12:22:41 μμ EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`store` (
  `store_id` INT NOT NULL,
  `square_meters` INT NOT NULL,
  `opening_hour` TIME NULL,
  `closing_hour` TIME NULL,
  `city` VARCHAR(45) NOT NULL,
  `postal_code` INT NOT NULL,
  `street_name` VARCHAR(45) NOT NULL,
  `street_number` INT NOT NULL,
  PRIMARY KEY (`store_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_type` (
  `type_id` INT NOT NULL,
  `name_of_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `current_price` REAL NULL,
  `special_store_label` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`has`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`has` (
  `corridor` INT NOT NULL,
  `shelf` INT NOT NULL,
  `store_id_has` INT NOT NULL,
  `product_id_has` INT NOT NULL,
  INDEX `store_id_idx` (`store_id_has` ASC) VISIBLE,
  INDEX `product_id_idx` (`product_id_has` ASC) VISIBLE,
  CONSTRAINT `product_id_has`
    FOREIGN KEY (`product_id_has`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `store_id_has`
    FOREIGN KEY (`store_id_has`)
    REFERENCES `mydb`.`store` (`store_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`past_prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`past_prices` (
  `date_of_change` DATE NOT NULL,
  `past_price_of_product` REAL NOT NULL,
  PRIMARY KEY (`date_of_change`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `transaction_id` INT NOT NULL,
  `time_of_transaction` TIME NOT NULL,
  `date_of_transaction` DATE NOT NULL,
  `means_of_payment` VARCHAR(45) NOT NULL,
  `total_cost` REAL NOT NULL,
  `total_amount_of_products` INT NOT NULL,
  PRIMARY KEY (`transaction_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `card_id` INT NOT NULL,
  `customers_city` VARCHAR(45) NOT NULL,
  `customers_postal_code` INT NOT NULL,
  `customers_street_name` VARCHAR(45) NOT NULL,
  `customers_street_number` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `marital_status` VARCHAR(45) NOT NULL,
  `number_of_kids` INT NOT NULL,
  `sex` VARCHAR(5) NOT NULL,
  `phone_number` BIGINT(20) NOT NULL,
  `birthday` DATE NOT NULL,
  PRIMARY KEY (`card_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer_points` (
  `total_cost_of_customer_purchases` INT NOT NULL,
  `card_id_points` INT NOT NULL,
  INDEX `card_id_idx` (`card_id_points` ASC) VISIBLE,
  CONSTRAINT `card_id_points`
    FOREIGN KEY (`card_id_points`)
    REFERENCES `mydb`.`customer` (`card_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchases` (
  `quantity` INT NOT NULL,
  `product_id_purchases` INT NOT NULL,
  `card_id_purchases` INT NOT NULL,
  `transaction_id_purchases` INT NOT NULL,
  `store_id_purchases` INT NOT NULL,
  INDEX `product_id_idx` (`product_id_purchases` ASC) VISIBLE,
  INDEX `card_id_idx` (`card_id_purchases` ASC) VISIBLE,
  INDEX `transaction_id_idx` (`transaction_id_purchases` ASC) VISIBLE,
  INDEX `store_id_purchases_idx` (`store_id_purchases` ASC) VISIBLE,
  CONSTRAINT `product_id_purchases`
    FOREIGN KEY (`product_id_purchases`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `card_id_purchases`
    FOREIGN KEY (`card_id_purchases`)
    REFERENCES `mydb`.`customer` (`card_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_id_purchases`
    FOREIGN KEY (`transaction_id_purchases`)
    REFERENCES `mydb`.`transaction` (`transaction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `store_id_purchases`
    FOREIGN KEY (`store_id_purchases`)
    REFERENCES `mydb`.`store` (`store_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contains` (
  `store_id_contains` INT NOT NULL,
  `type_id_contains` INT NOT NULL,
  INDEX `store_id_idx` (`store_id_contains` ASC) VISIBLE,
  INDEX `type_id_idx` (`type_id_contains` ASC) VISIBLE,
  CONSTRAINT `store_id_contains`
    FOREIGN KEY (`store_id_contains`)
    REFERENCES `mydb`.`store` (`store_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `type_id_contains`
    FOREIGN KEY (`type_id_contains`)
    REFERENCES `mydb`.`product_type` (`type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consists` (
  `product_id_consists` INT NOT NULL,
  `type_id_consists` INT NOT NULL,
  INDEX `product_id_idx` (`product_id_consists` ASC) VISIBLE,
  INDEX `type_id_idx` (`type_id_consists` ASC) VISIBLE,
  CONSTRAINT `product_id_consists`
    FOREIGN KEY (`product_id_consists`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `type_id_consists`
    FOREIGN KEY (`type_id_consists`)
    REFERENCES `mydb`.`product_type` (`type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`used_to_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`used_to_cost` (
  `product_id_used` INT NOT NULL,
  `date_of_change_used` DATE NOT NULL,
  INDEX `product_id_idx` (`product_id_used` ASC) VISIBLE,
  INDEX `date_of_change_idx` (`date_of_change_used` ASC) VISIBLE,
  CONSTRAINT `product_id_used`
    FOREIGN KEY (`product_id_used`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `date_of_change_used`
    FOREIGN KEY (`date_of_change_used`)
    REFERENCES `mydb`.`past_prices` (`date_of_change`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
